# Generated by Django 5.2.8 on 2025-11-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ELEC', 'Electrónica'), ('FOOD', 'Alimentos'), ('BOOK', 'Libros'), ('CLOT', 'Ropa')], max_length=4, verbose_name='Categoría')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (€)')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-date'],
            },
        ),
    ]
